# Site settings
title: Ruohan (Fleur) Feng
description: 'Cognitive Neuroscience · Psychology · Research Scientist'
url: 'rfeng77.github.io'
baseurl: ''
profilepic: '/images/Ruohan FENG photo.jpeg'
bkimage: '/images/image1.jpg'

author:
  name: 'Ruohan (Fleur) Feng'
  email: ruohan.feng@email.com
  linkedin_username: www.linkedin.com/in/ruohan-feng-138b59213

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
